In [1]:
# Libraries
import random
import numpy as np

In [2]:
#
# Dado un array de números enteros positivos, donde cada uno
# representa unidades de bloques apilados, debemos calcular cuantas unidades
# de agua quedarán atrapadas entre ellos.
#
# - Ejemplo: Dado el array [4, 0, 3, 6, 1, 3].
#
#         ⏹
#         ⏹
#   ⏹💧💧⏹
#   ⏹💧⏹⏹💧⏹
#   ⏹💧⏹⏹💧⏹
#   ⏹💧⏹⏹⏹⏹
#
#   Representando bloque con ⏹︎ y agua con 💧, quedarán atrapadas 7 unidades
#   de agua. Suponemos que existe un suelo impermeable en la parte inferior
#   que retiene el agua.
#

In [3]:
# generate random lenght of the array
Largo = random.randint(4, 12)
print("Largo: " + str(Largo) + "\n")
arreglo = [0] * Largo
#arreglo = [5,3,1,3,5,1,1,2,9,5,1]
arreglo = np.array(arreglo)
print("Empty Array: ")
print(arreglo)
print()

# Fill each position of array with random int numbers
for i in range(Largo):
    # print(str(random.randint(0, 10)) + " ")
    arreglo[i] = random.randint(0, 10)

print("Filled array: ")
print(arreglo)
print()

Largo: 5

Empty Array: 
[0 0 0 0 0]

Filled array: 
[ 1 10  3  9  4]



In [4]:
# Matriz creation

F = max(arreglo)
C = len(arreglo)
print("Filas = " + str(F) + " Columnas = " + str(C) + "\n")

# Matriz de dimensión (C, F) tipo string
matriz = np.full((F, C), ".", dtype=str)

print("Empty Matrix: ")
print(matriz[::-1, :])


Filas = 10 Columnas = 5

Empty Matrix: 
[['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']]


In [5]:
# Paint walls (blocks) in the Matrix

for i in range(len(arreglo)):
    temp = np.arange(arreglo[i], 0, -1)-1
    matriz[temp,i] = "X"

print(matriz[::-1, :])


[['.' 'X' '.' '.' '.']
 ['.' 'X' '.' 'X' '.']
 ['.' 'X' '.' 'X' '.']
 ['.' 'X' '.' 'X' '.']
 ['.' 'X' '.' 'X' '.']
 ['.' 'X' '.' 'X' '.']
 ['.' 'X' '.' 'X' 'X']
 ['.' 'X' 'X' 'X' 'X']
 ['.' 'X' 'X' 'X' 'X']
 ['X' 'X' 'X' 'X' 'X']]


In [6]:
# Look for spaces that can filled with Water

#columna_temp = 3
#temp_range = np.arange( columna_temp + 1, len(arreglo), 1) # look values into right indexes of array
#print(arreglo[temp_range])

temp_f = range(max(arreglo))
temp_c = range(len(arreglo))

for fila in temp_f:
    for columna in temp_c[1:-1]: # omito la primera y la última pared
        
        # Condition 1: # check if there is wall or water to the left
        # -----------------------------------------------------------------------------
        # print("Fila: " + str(fila) + " Columna: " + str(columna))
        # look if to the left there is water or wall
        if((matriz[fila,columna-1] == "X" or matriz[fila,columna-1] == "O")): 
            temp = max(arreglo[np.arange( columna + 1, len(arreglo), 1)]) 
            # print("fila " + str(fila) + " columna " + str(columna) + " temp " + str(temp))
            
        # Condition 2: # look values into right indexes of array
        # -----------------------------------------------------------------------------
            # print("F: " + str(fila) + " C: " + str(columna) + " Max right: " + str(max(arreglo[temp_range])))
            # if(fila <= temp): # look if there is a wall to the right
            temp = "X" in matriz[fila, columna + 1:]
            if temp:

        # Condition 3: that space row,column must be empty (".")
        # -----------------------------------------------------------------------------
                if(matriz[fila,columna] == "."):
                    # print( "columna = " + str(columna) + " fila = " + str(fila) + " celda: " + str(matriz[fila,columna]) + " array: " + str(arreglo[columna]))
                    matriz[fila, columna] = "O"

# final matrix already painted
print("Output matrix for: ")
print(arreglo)
print()
print(matriz[::-1, :])
    

Output matrix for: 
[ 1 10  3  9  4]

[['.' 'X' '.' '.' '.']
 ['.' 'X' 'O' 'X' '.']
 ['.' 'X' 'O' 'X' '.']
 ['.' 'X' 'O' 'X' '.']
 ['.' 'X' 'O' 'X' '.']
 ['.' 'X' 'O' 'X' '.']
 ['.' 'X' 'O' 'X' 'X']
 ['.' 'X' 'X' 'X' 'X']
 ['.' 'X' 'X' 'X' 'X']
 ['X' 'X' 'X' 'X' 'X']]
